In [1]:
import pandas as pd

In [5]:
bond = pd.read_csv("data/jamesbond.csv", index_col="Movie").sort_index()
bond.head(2)

,Year,Bond,Director,Composer,Writer,Cinematographer,Depicted_Film_Loc,Shooting_Loc,Bond_Car_MFG,Bond_Girl_Nat,...,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Conquests,Martinis,BJB,Kills_Bond,Kills_Others,Top_100,Video_Game
Movie,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,John Barry,Michael G. Wilson & Richard Maibaum,Alan Hume,"Russia, Great Britain, France, United States","England, Switzerland, Iceland, France, United ...",Rolls Royce,"American, Jamaican, Sweedish, Nigerian",...,131,6.2,4.7,4,0,2,5,57,1,0
Casino Royale,2006,Daniel Craig,Martin Campbell,David Arnold,"Neal Purvis, Robert Wade & Paul Haggis",Phil Méheux,"Czech Republic, Pakistan, Uganda, Madagascar, ...","England, Italy, Czech republic, Bahamas, Unite...",Aston Martin,"French, Italian",...,144,7.9,7.8,2,3,1,11,11,1,0